import { File } from "parse-diff";
import { getAISummary, createSummaryPrompt } from "./aiService";
import { PRDetails } from "./types";

export async function summarizeChanges(
  parsedDiff: File[],
  prDetails: PRDetails
): Promise<string | null> {
  const filesChanged = parsedDiff.map((file) => file.to || "").join(", ");

  const commitMessages = prDetails.commits
    .map((c) => `- ${c.message}`)
    .join("\n");

  let diffSummary = "";
  for (const file of parsedDiff) {
    diffSummary += `${file.to || "unknown file"}: ${file.chunks.length} change(s) detected.\n`;
  }

  const prompt = createSummaryPrompt(
    filesChanged,
    prDetails.title,
    prDetails.description,
    commitMessages,
    diffSummary
  );

  const summary = await getAISummary(prompt);

  if (!summary) return null;

  // Format the summary with better spacing and structure
  const formattedSummary = `## PR Summary

${summary
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line)
  .join("\n\n")}

### Files Changed
${parsedDiff.map((file) => `- \`${file.to || "unknown file"}\``).join("\n")}

<sub>Generated by [pr-summarizer](https://github.com/ashgw/pr-summarizer)</sub>`;

  return formattedSummary;
}
